### ISSUE TITLE
这个知道怎么解决么？KeyError: '__flags'

### ISSUE THREAD

**Issue by luluforever** [XingyanLee/Chinese-NER-#4]
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    if __name__ == "__main__":
  File "D:\python3\lib\site-packages\tensorflow\python\platform\app.py", line 40
, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\python3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "D:\python3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 84, in main
    args = Arguments()
  File "D:\NER\bilstm _Attention_crf-NER-master\bilstm _Attention_crf-NER\src\Ar
guments.py", line 52, in tf_apps
    for k in FLAGS.__dict__['__flags'].keys():
KeyError: '__flags'

**Comment by Evaoooos** [comment]
check tf.version==1.3
